<template>
  <div class="wrapper">
      <ul class="content">
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      <li>分类列biao</li>
      </ul>
  </div>
</template>
<script>
import BScroll from 'better-scroll'
export default {
  name:'Category',
  data(){
    return{
      bsroll:null
    }
  },
  mounted(){
    this.bsroll = new BScroll(document.querySelector('.wrapper'),{

    })
  }
}
</script>
<style scoped>
.wrapper{
  height: 150px;
  background-color: pink;
  overflow: hidden;
}
</style>